# ####################################
# USED ONLY FOR AUTOMATIC UNIT TESTS #
# ####################################

proxy:
  build: proxy

backend:
  build: backend

backendirods:
  build: backendirods

backendcentos:
  build: backendcentos

angular:
  build: angular

react:
  build: react

icat:
  # image: b2safe/server:icat
  build: icat

# b2safe:
#   # NOTE: this depends on icat
#   build: b2safe

ftp:
  build: ftp

rabbitmq:
  build: rabbitmq

dind:
  build: dind
  privileged: true

