# ####################################
# USED ONLY FOR AUTOMATIC UNIT TESTS #
# ####################################

proxy:
  build: proxy

backend:
  build: backend

backendirods:
  build: backendirods

angular:
  build: angular

react:
  build: react

icat:
  build: icat

ftp:
  build: ftp

rabbitmq:
  build: rabbitmq

dind:
  build: dind
  privileged: true

